import { useLazyQuery, useQuery } from '@apollo/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import { POSTS_QUERY } from '../graphql/queries/query'
import { UserData } from '../graphql/types/types'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Header from './components/header'

const Home: NextPage = () => {
  // const { loading, error, data } = useQuery<UserData>(POSTS_QUERY);
  // if (loading) return <p>Loading...</p>;
  // if (error) return <p>Error: {JSON.stringify(error)}</p>;
  // if (!data) return null;
  const [loaddata, { called, loading, error, data }] = useLazyQuery<UserData>(POSTS_QUERY);

  if (data) {
    console.log(data);
  }
   
  async function testEvent () {
    await loaddata();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      
      <div className="search-area-img">
        <img className="search-area-top-img" src='/assets/img/searchArea.jpg'></img> 
        <div className="search-area-input">
          <input className="search-area-input-text" type="text"></input>
          <button className="search-area-input-button">検索</button>
        </div>
      </div>
    </div>
  )
}

export default Home
